# 修改 `redo-help-doc/_config.yml` 文件的内容，加入以下配置：
#baseurl: "/kc-intro"
baseurl: ""
source: "_src"
title: "kc intro"
destination: "_www"
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
  - footnotes
sass:
  style: :compressed
  sass_dir: _css

permalink: category/docs/:title.html

collections:
  category:
    output: true
    permalink: category/:path/index.html
  sub_category:
    output: true
    permalink: category/:path/index.html
  articles:
    output: true
    permalink: articles/:title.html
